[tox]
requires =
  tox>=4.4.10
envlist = pylint,mypy,black,pytest

[testenv]
skip_install = true
skipsdist = true
usedevelop = false
passenv = *
setenv =
  PIP_EXTRA_INDEX_URL=https://pypi.org/simple
deps =
  -r {tox_root}/dev_requirements.txt
install_command = python -m pip install {opts} {packages}

[testenv:mypy]
description = Typecheck the package with mypy (version {[testenv:mypy]mypy_version})
mypy_version = 1.18.1
skip_install = true
skipsdist = true
usedevelop = true
deps =
  {[testenv]deps}
  mypy=={[testenv:mypy]mypy_version}
commands =
    python -m pip install -e {tox_root}
    python {repository_root}/eng/tox/run_mypy.py -t {tox_root}

[testenv:pylint]
description = Lint the package with pylint (version {[testenv:pylint]pylint_version})
pylint_version = 3.2.7
skip_install = true
skipsdist = true
usedevelop = false
deps =
  {[testenv]deps}
  pylint=={[testenv:pylint]pylint_version}
commands =
    python -m pip install -e {tox_root}
    python {repository_root}/eng/tox/run_pylint.py -t {tox_root}

[testenv:black]
description = Format code with black
skip_install = true
skipsdist = true
deps =
  black>=24.0
commands =
    python -m black {tox_root}/src {tox_root}/tests {tox_root}/samples

[testenv:pytest]
description = Run tests with pytest
skip_install = true
skipsdist = true
deps =
  {[testenv]deps}
  pytest>=8.0
commands =
    python -m pip install -e {tox_root}
    python -m pytest {tox_root}/tests {posargs}
